// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Order struct {
	ID                 pgtype.UUID
	UserID             pgtype.UUID
	Status             string
	TotalCents         int64
	Currency           string
	ReservationID      pgtype.UUID
	PaymentID          pgtype.UUID
	IdempotencyKey     *string
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	AuthorizationUrl   string
	ShippingMethodID   pgtype.UUID
	ShippingMethodName string
	ShippingCents      int64
	ShipRecipient      string
	ShipPhone          string
	ShipLine1          string
	ShipLine2          string
	ShipCity           string
	ShipState          string
	ShipPostalCode     string
	ShipCountry        string
}

type OrderItem struct {
	ID         pgtype.UUID
	OrderID    pgtype.UUID
	ProductID  pgtype.UUID
	Name       string
	PriceCents int64
	Quantity   int32
}

type Outbox struct {
	ID          pgtype.UUID
	Topic       string
	Payload     []byte
	CreatedAt   pgtype.Timestamptz
	PublishedAt pgtype.Timestamptz
}

type ShippingMethod struct {
	ID          pgtype.UUID
	Name        string
	Description string
	PriceCents  int64
	SortOrder   int32
	Active      bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}
