// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (user_id, status, total_cents, currency, reservation_id, idempotency_key)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, status, total_cents, currency, reservation_id, payment_id, idempotency_key, created_at, updated_at
`

type CreateOrderParams struct {
	UserID         pgtype.UUID
	Status         string
	TotalCents     int64
	Currency       string
	ReservationID  pgtype.UUID
	IdempotencyKey *string
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.UserID,
		arg.Status,
		arg.TotalCents,
		arg.Currency,
		arg.ReservationID,
		arg.IdempotencyKey,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.TotalCents,
		&i.Currency,
		&i.ReservationID,
		&i.PaymentID,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :exec
INSERT INTO order_items (order_id, product_id, name, price_cents, quantity)
VALUES ($1, $2, $3, $4, $5)
`

type CreateOrderItemParams struct {
	OrderID    pgtype.UUID
	ProductID  pgtype.UUID
	Name       string
	PriceCents int64
	Quantity   int32
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) error {
	_, err := q.db.Exec(ctx, createOrderItem,
		arg.OrderID,
		arg.ProductID,
		arg.Name,
		arg.PriceCents,
		arg.Quantity,
	)
	return err
}

const getOrder = `-- name: GetOrder :one
SELECT id, user_id, status, total_cents, currency, reservation_id, payment_id, idempotency_key, created_at, updated_at FROM orders WHERE id = $1
`

func (q *Queries) GetOrder(ctx context.Context, id pgtype.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.TotalCents,
		&i.Currency,
		&i.ReservationID,
		&i.PaymentID,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderByIdempotencyKey = `-- name: GetOrderByIdempotencyKey :one
SELECT id, user_id, status, total_cents, currency, reservation_id, payment_id, idempotency_key, created_at, updated_at FROM orders WHERE idempotency_key = $1
`

func (q *Queries) GetOrderByIdempotencyKey(ctx context.Context, idempotencyKey *string) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByIdempotencyKey, idempotencyKey)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.TotalCents,
		&i.Currency,
		&i.ReservationID,
		&i.PaymentID,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertOutbox = `-- name: InsertOutbox :exec
INSERT INTO outbox (topic, payload) VALUES ($1, $2)
`

type InsertOutboxParams struct {
	Topic   string
	Payload []byte
}

func (q *Queries) InsertOutbox(ctx context.Context, arg InsertOutboxParams) error {
	_, err := q.db.Exec(ctx, insertOutbox, arg.Topic, arg.Payload)
	return err
}

const listOrderItems = `-- name: ListOrderItems :many
SELECT id, order_id, product_id, name, price_cents, quantity FROM order_items WHERE order_id = $1 ORDER BY name
`

func (q *Queries) ListOrderItems(ctx context.Context, orderID pgtype.UUID) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, listOrderItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderItem
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProductID,
			&i.Name,
			&i.PriceCents,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByUser = `-- name: ListOrdersByUser :many
SELECT id, user_id, status, total_cents, currency, reservation_id, payment_id, idempotency_key, created_at, updated_at FROM orders WHERE user_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListOrdersByUserParams struct {
	UserID pgtype.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) ListOrdersByUser(ctx context.Context, arg ListOrdersByUserParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.TotalCents,
			&i.Currency,
			&i.ReservationID,
			&i.PaymentID,
			&i.IdempotencyKey,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnpublishedOutbox = `-- name: ListUnpublishedOutbox :many
SELECT id, topic, payload, created_at, published_at FROM outbox WHERE published_at IS NULL ORDER BY created_at LIMIT $1
`

func (q *Queries) ListUnpublishedOutbox(ctx context.Context, limit int32) ([]Outbox, error) {
	rows, err := q.db.Query(ctx, listUnpublishedOutbox, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Outbox
	for rows.Next() {
		var i Outbox
		if err := rows.Scan(
			&i.ID,
			&i.Topic,
			&i.Payload,
			&i.CreatedAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxPublished = `-- name: MarkOutboxPublished :exec
UPDATE outbox SET published_at = now() WHERE id = $1
`

func (q *Queries) MarkOutboxPublished(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markOutboxPublished, id)
	return err
}

const setOrderPaymentAndStatus = `-- name: SetOrderPaymentAndStatus :one
UPDATE orders SET payment_id = $2, status = $3, updated_at = now() WHERE id = $1 RETURNING id, user_id, status, total_cents, currency, reservation_id, payment_id, idempotency_key, created_at, updated_at
`

type SetOrderPaymentAndStatusParams struct {
	ID        pgtype.UUID
	PaymentID pgtype.UUID
	Status    string
}

func (q *Queries) SetOrderPaymentAndStatus(ctx context.Context, arg SetOrderPaymentAndStatusParams) (Order, error) {
	row := q.db.QueryRow(ctx, setOrderPaymentAndStatus, arg.ID, arg.PaymentID, arg.Status)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.TotalCents,
		&i.Currency,
		&i.ReservationID,
		&i.PaymentID,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE orders SET status = $2, updated_at = now() WHERE id = $1 RETURNING id, user_id, status, total_cents, currency, reservation_id, payment_id, idempotency_key, created_at, updated_at
`

type UpdateOrderStatusParams struct {
	ID     pgtype.UUID
	Status string
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderStatus, arg.ID, arg.Status)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.TotalCents,
		&i.Currency,
		&i.ReservationID,
		&i.PaymentID,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
