// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (id, user_id, status, total_cents, currency, reservation_id, idempotency_key)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, status, total_cents, currency, reservation_id, payment_id, idempotency_key, created_at, updated_at, authorization_url
`

type CreateOrderParams struct {
	ID             pgtype.UUID
	UserID         pgtype.UUID
	Status         string
	TotalCents     int64
	Currency       string
	ReservationID  pgtype.UUID
	IdempotencyKey *string
}

// id is supplied (not defaulted) so reservation_id can equal the order id — the
// saga reserves stock under the order's own id, making ReserveStock idempotent.
func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.ID,
		arg.UserID,
		arg.Status,
		arg.TotalCents,
		arg.Currency,
		arg.ReservationID,
		arg.IdempotencyKey,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.TotalCents,
		&i.Currency,
		&i.ReservationID,
		&i.PaymentID,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthorizationUrl,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :exec
INSERT INTO order_items (order_id, product_id, name, price_cents, quantity)
VALUES ($1, $2, $3, $4, $5)
`

type CreateOrderItemParams struct {
	OrderID    pgtype.UUID
	ProductID  pgtype.UUID
	Name       string
	PriceCents int64
	Quantity   int32
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) error {
	_, err := q.db.Exec(ctx, createOrderItem,
		arg.OrderID,
		arg.ProductID,
		arg.Name,
		arg.PriceCents,
		arg.Quantity,
	)
	return err
}

const createShippingMethod = `-- name: CreateShippingMethod :one

INSERT INTO shipping_methods (name, description, price_cents, sort_order, active)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, description, price_cents, sort_order, active, created_at, updated_at
`

type CreateShippingMethodParams struct {
	Name        string
	Description string
	PriceCents  int64
	SortOrder   int32
	Active      bool
}

// Shipping methods.
func (q *Queries) CreateShippingMethod(ctx context.Context, arg CreateShippingMethodParams) (ShippingMethod, error) {
	row := q.db.QueryRow(ctx, createShippingMethod,
		arg.Name,
		arg.Description,
		arg.PriceCents,
		arg.SortOrder,
		arg.Active,
	)
	var i ShippingMethod
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PriceCents,
		&i.SortOrder,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteShippingMethod = `-- name: DeleteShippingMethod :execrows
DELETE FROM shipping_methods WHERE id = $1
`

func (q *Queries) DeleteShippingMethod(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteShippingMethod, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getOrder = `-- name: GetOrder :one
SELECT id, user_id, status, total_cents, currency, reservation_id, payment_id, idempotency_key, created_at, updated_at, authorization_url FROM orders WHERE id = $1
`

func (q *Queries) GetOrder(ctx context.Context, id pgtype.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.TotalCents,
		&i.Currency,
		&i.ReservationID,
		&i.PaymentID,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthorizationUrl,
	)
	return i, err
}

const getOrderByIdempotencyKey = `-- name: GetOrderByIdempotencyKey :one
SELECT id, user_id, status, total_cents, currency, reservation_id, payment_id, idempotency_key, created_at, updated_at, authorization_url FROM orders WHERE idempotency_key = $1
`

func (q *Queries) GetOrderByIdempotencyKey(ctx context.Context, idempotencyKey *string) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByIdempotencyKey, idempotencyKey)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.TotalCents,
		&i.Currency,
		&i.ReservationID,
		&i.PaymentID,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthorizationUrl,
	)
	return i, err
}

const getShippingMethod = `-- name: GetShippingMethod :one
SELECT id, name, description, price_cents, sort_order, active, created_at, updated_at FROM shipping_methods WHERE id = $1
`

func (q *Queries) GetShippingMethod(ctx context.Context, id pgtype.UUID) (ShippingMethod, error) {
	row := q.db.QueryRow(ctx, getShippingMethod, id)
	var i ShippingMethod
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PriceCents,
		&i.SortOrder,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertOutbox = `-- name: InsertOutbox :exec
INSERT INTO outbox (topic, payload) VALUES ($1, $2)
`

type InsertOutboxParams struct {
	Topic   string
	Payload []byte
}

func (q *Queries) InsertOutbox(ctx context.Context, arg InsertOutboxParams) error {
	_, err := q.db.Exec(ctx, insertOutbox, arg.Topic, arg.Payload)
	return err
}

const listActiveShippingMethods = `-- name: ListActiveShippingMethods :many
SELECT id, name, description, price_cents, sort_order, active, created_at, updated_at FROM shipping_methods WHERE active ORDER BY sort_order, name
`

func (q *Queries) ListActiveShippingMethods(ctx context.Context) ([]ShippingMethod, error) {
	rows, err := q.db.Query(ctx, listActiveShippingMethods)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShippingMethod
	for rows.Next() {
		var i ShippingMethod
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.PriceCents,
			&i.SortOrder,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderItems = `-- name: ListOrderItems :many
SELECT id, order_id, product_id, name, price_cents, quantity FROM order_items WHERE order_id = $1 ORDER BY name
`

func (q *Queries) ListOrderItems(ctx context.Context, orderID pgtype.UUID) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, listOrderItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderItem
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProductID,
			&i.Name,
			&i.PriceCents,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByUser = `-- name: ListOrdersByUser :many
SELECT id, user_id, status, total_cents, currency, reservation_id, payment_id, idempotency_key, created_at, updated_at, authorization_url FROM orders WHERE user_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListOrdersByUserParams struct {
	UserID pgtype.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) ListOrdersByUser(ctx context.Context, arg ListOrdersByUserParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.TotalCents,
			&i.Currency,
			&i.ReservationID,
			&i.PaymentID,
			&i.IdempotencyKey,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorizationUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShippingMethods = `-- name: ListShippingMethods :many
SELECT id, name, description, price_cents, sort_order, active, created_at, updated_at FROM shipping_methods ORDER BY sort_order, name
`

func (q *Queries) ListShippingMethods(ctx context.Context) ([]ShippingMethod, error) {
	rows, err := q.db.Query(ctx, listShippingMethods)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShippingMethod
	for rows.Next() {
		var i ShippingMethod
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.PriceCents,
			&i.SortOrder,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnpublishedOutbox = `-- name: ListUnpublishedOutbox :many
SELECT id, topic, payload, created_at, published_at FROM outbox WHERE published_at IS NULL ORDER BY created_at LIMIT $1
`

func (q *Queries) ListUnpublishedOutbox(ctx context.Context, limit int32) ([]Outbox, error) {
	rows, err := q.db.Query(ctx, listUnpublishedOutbox, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Outbox
	for rows.Next() {
		var i Outbox
		if err := rows.Scan(
			&i.ID,
			&i.Topic,
			&i.Payload,
			&i.CreatedAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOrderPaymentPending = `-- name: MarkOrderPaymentPending :one
UPDATE orders
SET status = 'PAYMENT_PENDING', payment_id = $2, authorization_url = $3, updated_at = now()
WHERE id = $1
RETURNING id, user_id, status, total_cents, currency, reservation_id, payment_id, idempotency_key, created_at, updated_at, authorization_url
`

type MarkOrderPaymentPendingParams struct {
	ID               pgtype.UUID
	PaymentID        pgtype.UUID
	AuthorizationUrl string
}

// The async "start" half records the initialized payment and its authorization URL
// as the order enters PAYMENT_PENDING, awaiting the webhook-driven resume.
func (q *Queries) MarkOrderPaymentPending(ctx context.Context, arg MarkOrderPaymentPendingParams) (Order, error) {
	row := q.db.QueryRow(ctx, markOrderPaymentPending, arg.ID, arg.PaymentID, arg.AuthorizationUrl)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.TotalCents,
		&i.Currency,
		&i.ReservationID,
		&i.PaymentID,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthorizationUrl,
	)
	return i, err
}

const markOutboxPublished = `-- name: MarkOutboxPublished :exec
UPDATE outbox SET published_at = now() WHERE id = $1
`

func (q *Queries) MarkOutboxPublished(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markOutboxPublished, id)
	return err
}

const setOrderPaymentAndStatus = `-- name: SetOrderPaymentAndStatus :one
UPDATE orders SET payment_id = $2, status = $3, updated_at = now() WHERE id = $1 RETURNING id, user_id, status, total_cents, currency, reservation_id, payment_id, idempotency_key, created_at, updated_at, authorization_url
`

type SetOrderPaymentAndStatusParams struct {
	ID        pgtype.UUID
	PaymentID pgtype.UUID
	Status    string
}

func (q *Queries) SetOrderPaymentAndStatus(ctx context.Context, arg SetOrderPaymentAndStatusParams) (Order, error) {
	row := q.db.QueryRow(ctx, setOrderPaymentAndStatus, arg.ID, arg.PaymentID, arg.Status)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.TotalCents,
		&i.Currency,
		&i.ReservationID,
		&i.PaymentID,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthorizationUrl,
	)
	return i, err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE orders SET status = $2, updated_at = now() WHERE id = $1 RETURNING id, user_id, status, total_cents, currency, reservation_id, payment_id, idempotency_key, created_at, updated_at, authorization_url
`

type UpdateOrderStatusParams struct {
	ID     pgtype.UUID
	Status string
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderStatus, arg.ID, arg.Status)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.TotalCents,
		&i.Currency,
		&i.ReservationID,
		&i.PaymentID,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthorizationUrl,
	)
	return i, err
}

const updateShippingMethod = `-- name: UpdateShippingMethod :one
UPDATE shipping_methods
SET name = $2, description = $3, price_cents = $4, sort_order = $5, active = $6, updated_at = now()
WHERE id = $1
RETURNING id, name, description, price_cents, sort_order, active, created_at, updated_at
`

type UpdateShippingMethodParams struct {
	ID          pgtype.UUID
	Name        string
	Description string
	PriceCents  int64
	SortOrder   int32
	Active      bool
}

func (q *Queries) UpdateShippingMethod(ctx context.Context, arg UpdateShippingMethodParams) (ShippingMethod, error) {
	row := q.db.QueryRow(ctx, updateShippingMethod,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.PriceCents,
		arg.SortOrder,
		arg.Active,
	)
	var i ShippingMethod
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PriceCents,
		&i.SortOrder,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
