// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Notification struct {
	ID       pgtype.UUID
	EventID  pgtype.UUID
	UserID   pgtype.UUID
	Channel  string
	Template string
	Payload  []byte
	SentAt   pgtype.Timestamptz
}
