// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countByEventID = `-- name: CountByEventID :one
SELECT count(*) FROM notifications WHERE event_id = $1
`

func (q *Queries) CountByEventID(ctx context.Context, eventID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countByEventID, eventID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertNotification = `-- name: InsertNotification :exec
INSERT INTO notifications (event_id, user_id, channel, template, payload)
VALUES ($1, $2, $3, $4, $5)
`

type InsertNotificationParams struct {
	EventID  pgtype.UUID
	UserID   pgtype.UUID
	Channel  string
	Template string
	Payload  []byte
}

// Fails with a unique violation if event_id was already processed (the dedup gate).
func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) error {
	_, err := q.db.Exec(ctx, insertNotification,
		arg.EventID,
		arg.UserID,
		arg.Channel,
		arg.Template,
		arg.Payload,
	)
	return err
}

const listByUser = `-- name: ListByUser :many
SELECT id, event_id, user_id, channel, template, payload, sent_at FROM notifications WHERE user_id = $1 ORDER BY sent_at DESC LIMIT $2
`

type ListByUserParams struct {
	UserID pgtype.UUID
	Limit  int32
}

func (q *Queries) ListByUser(ctx context.Context, arg ListByUserParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listByUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.UserID,
			&i.Channel,
			&i.Template,
			&i.Payload,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
