// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Address struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	Label      string
	Recipient  string
	Phone      string
	Line1      string
	Line2      string
	City       string
	State      string
	PostalCode string
	Country    string
	IsDefault  bool
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type PasswordResetToken struct {
	Token     pgtype.UUID
	UserID    pgtype.UUID
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type RefreshToken struct {
	Jti       pgtype.UUID
	UserID    pgtype.UUID
	ExpiresAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID            pgtype.UUID
	Email         string
	PasswordHash  string
	FullName      string
	Role          string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	EmailVerified bool
	DeletedAt     pgtype.Timestamptz
}

type VerificationToken struct {
	Token     pgtype.UUID
	UserID    pgtype.UUID
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}
