// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type RefreshToken struct {
	Jti       pgtype.UUID
	UserID    pgtype.UUID
	ExpiresAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID            pgtype.UUID
	Email         string
	PasswordHash  string
	FullName      string
	Role          string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	EmailVerified bool
}

type VerificationToken struct {
	Token     pgtype.UUID
	UserID    pgtype.UUID
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}
