// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID   pgtype.UUID
	Name string
	Slug string
}

type Inventory struct {
	ProductID pgtype.UUID
	Quantity  int32
	Reserved  int32
	Version   int32
}

type Product struct {
	ID          pgtype.UUID
	Sku         string
	Name        string
	Description string
	PriceCents  int64
	Currency    string
	CategoryID  pgtype.UUID
	CreatedAt   pgtype.Timestamptz
}
