// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countProducts = `-- name: CountProducts :one
SELECT count(*) FROM products
WHERE $1::uuid IS NULL
   OR category_id = $1
`

// Total for the same filter, so ListProducts can report total alongside the page.
func (q *Queries) CountProducts(ctx context.Context, categoryID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countProducts, categoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCategory = `-- name: CreateCategory :one

INSERT INTO categories (name, slug)
VALUES ($1, $2)
RETURNING id, name, slug
`

type CreateCategoryParams struct {
	Name string
	Slug string
}

// Catalog read/write queries. Each is annotated for sqlc:
//
//	:one  -> returns exactly one row  (Go: (T, error))
//	:many -> returns many rows         (Go: ([]T, error))
//	:exec -> returns no rows           (Go: error)
//
// $1, $2, ... are positional params; sqlc.narg(name) is a NULLABLE named param.
func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory, arg.Name, arg.Slug)
	var i Category
	err := row.Scan(&i.ID, &i.Name, &i.Slug)
	return i, err
}

const createInventory = `-- name: CreateInventory :one
INSERT INTO inventory (product_id, quantity)
VALUES ($1, $2)
RETURNING product_id, quantity, reserved, version
`

type CreateInventoryParams struct {
	ProductID pgtype.UUID
	Quantity  int32
}

func (q *Queries) CreateInventory(ctx context.Context, arg CreateInventoryParams) (Inventory, error) {
	row := q.db.QueryRow(ctx, createInventory, arg.ProductID, arg.Quantity)
	var i Inventory
	err := row.Scan(
		&i.ProductID,
		&i.Quantity,
		&i.Reserved,
		&i.Version,
	)
	return i, err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (sku, name, description, price_cents, currency, category_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, sku, name, description, price_cents, currency, category_id, created_at
`

type CreateProductParams struct {
	Sku         string
	Name        string
	Description string
	PriceCents  int64
	Currency    string
	CategoryID  pgtype.UUID
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.Sku,
		arg.Name,
		arg.Description,
		arg.PriceCents,
		arg.Currency,
		arg.CategoryID,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Name,
		&i.Description,
		&i.PriceCents,
		&i.Currency,
		&i.CategoryID,
		&i.CreatedAt,
	)
	return i, err
}

const getInventory = `-- name: GetInventory :one
SELECT product_id, quantity, reserved, version FROM inventory
WHERE product_id = $1
`

func (q *Queries) GetInventory(ctx context.Context, productID pgtype.UUID) (Inventory, error) {
	row := q.db.QueryRow(ctx, getInventory, productID)
	var i Inventory
	err := row.Scan(
		&i.ProductID,
		&i.Quantity,
		&i.Reserved,
		&i.Version,
	)
	return i, err
}

const getProduct = `-- name: GetProduct :one
SELECT id, sku, name, description, price_cents, currency, category_id, created_at FROM products
WHERE id = $1
`

func (q *Queries) GetProduct(ctx context.Context, id pgtype.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Name,
		&i.Description,
		&i.PriceCents,
		&i.Currency,
		&i.CategoryID,
		&i.CreatedAt,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, sku, name, description, price_cents, currency, category_id, created_at FROM products
WHERE $3::uuid IS NULL
   OR category_id = $3
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListProductsParams struct {
	Limit      int32
	Offset     int32
	CategoryID pgtype.UUID
}

// Optional category filter via a nullable named arg: when category_id is NULL the
// first branch short-circuits and every row matches.
func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts, arg.Limit, arg.Offset, arg.CategoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Sku,
			&i.Name,
			&i.Description,
			&i.PriceCents,
			&i.Currency,
			&i.CategoryID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
