// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const commitInventory = `-- name: CommitInventory :exec
UPDATE inventory
SET quantity = quantity - $1,
    reserved = reserved - $1,
    version  = version + 1
WHERE product_id = $2
`

type CommitInventoryParams struct {
	Quantity  int32
	ProductID pgtype.UUID
}

// Finalize: the goods actually leave — drop BOTH quantity and reserved.
func (q *Queries) CommitInventory(ctx context.Context, arg CommitInventoryParams) error {
	_, err := q.db.Exec(ctx, commitInventory, arg.Quantity, arg.ProductID)
	return err
}

const countProducts = `-- name: CountProducts :one
SELECT count(*) FROM products
WHERE $1::uuid IS NULL
   OR category_id = $1
`

// Total for the same filter, so ListProducts can report total alongside the page.
func (q *Queries) CountProducts(ctx context.Context, categoryID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countProducts, categoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCategory = `-- name: CreateCategory :one

INSERT INTO categories (name, slug)
VALUES ($1, $2)
RETURNING id, name, slug
`

type CreateCategoryParams struct {
	Name string
	Slug string
}

// Catalog read/write queries. Each is annotated for sqlc:
//
//	:one  -> returns exactly one row  (Go: (T, error))
//	:many -> returns many rows         (Go: ([]T, error))
//	:exec -> returns no rows           (Go: error)
//
// $1, $2, ... are positional params; sqlc.narg(name) is a NULLABLE named param.
func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory, arg.Name, arg.Slug)
	var i Category
	err := row.Scan(&i.ID, &i.Name, &i.Slug)
	return i, err
}

const createInventory = `-- name: CreateInventory :one
INSERT INTO inventory (product_id, quantity)
VALUES ($1, $2)
RETURNING product_id, quantity, reserved, version
`

type CreateInventoryParams struct {
	ProductID pgtype.UUID
	Quantity  int32
}

func (q *Queries) CreateInventory(ctx context.Context, arg CreateInventoryParams) (Inventory, error) {
	row := q.db.QueryRow(ctx, createInventory, arg.ProductID, arg.Quantity)
	var i Inventory
	err := row.Scan(
		&i.ProductID,
		&i.Quantity,
		&i.Reserved,
		&i.Version,
	)
	return i, err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (sku, name, description, price_cents, currency, category_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, sku, name, description, price_cents, currency, category_id, created_at
`

type CreateProductParams struct {
	Sku         string
	Name        string
	Description string
	PriceCents  int64
	Currency    string
	CategoryID  pgtype.UUID
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.Sku,
		arg.Name,
		arg.Description,
		arg.PriceCents,
		arg.Currency,
		arg.CategoryID,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Name,
		&i.Description,
		&i.PriceCents,
		&i.Currency,
		&i.CategoryID,
		&i.CreatedAt,
	)
	return i, err
}

const getInventory = `-- name: GetInventory :one
SELECT product_id, quantity, reserved, version FROM inventory
WHERE product_id = $1
`

func (q *Queries) GetInventory(ctx context.Context, productID pgtype.UUID) (Inventory, error) {
	row := q.db.QueryRow(ctx, getInventory, productID)
	var i Inventory
	err := row.Scan(
		&i.ProductID,
		&i.Quantity,
		&i.Reserved,
		&i.Version,
	)
	return i, err
}

const getProduct = `-- name: GetProduct :one
SELECT id, sku, name, description, price_cents, currency, category_id, created_at FROM products
WHERE id = $1
`

func (q *Queries) GetProduct(ctx context.Context, id pgtype.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Name,
		&i.Description,
		&i.PriceCents,
		&i.Currency,
		&i.CategoryID,
		&i.CreatedAt,
	)
	return i, err
}

const getProductWithInventory = `-- name: GetProductWithInventory :one
SELECT p.id, p.sku, p.name, p.description, p.price_cents, p.currency, p.category_id, p.created_at, i.quantity, i.reserved, (i.quantity - i.reserved)::int AS available
FROM products p
JOIN inventory i ON i.product_id = p.id
WHERE p.id = $1
`

type GetProductWithInventoryRow struct {
	ID          pgtype.UUID
	Sku         string
	Name        string
	Description string
	PriceCents  int64
	Currency    string
	CategoryID  pgtype.UUID
	CreatedAt   pgtype.Timestamptz
	Quantity    int32
	Reserved    int32
	Available   int32
}

// Product detail joined with live stock; available = quantity - reserved.
func (q *Queries) GetProductWithInventory(ctx context.Context, id pgtype.UUID) (GetProductWithInventoryRow, error) {
	row := q.db.QueryRow(ctx, getProductWithInventory, id)
	var i GetProductWithInventoryRow
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Name,
		&i.Description,
		&i.PriceCents,
		&i.Currency,
		&i.CategoryID,
		&i.CreatedAt,
		&i.Quantity,
		&i.Reserved,
		&i.Available,
	)
	return i, err
}

const getReservationStatusForUpdate = `-- name: GetReservationStatusForUpdate :one
SELECT status FROM stock_reservations WHERE id = $1 FOR UPDATE
`

// SELECT ... FOR UPDATE locks the reservation row for the rest of the transaction,
// serializing concurrent Release/Commit of the same reservation so they can't both
// act on it (idempotency under contention).
func (q *Queries) GetReservationStatusForUpdate(ctx context.Context, id pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getReservationStatusForUpdate, id)
	var status string
	err := row.Scan(&status)
	return status, err
}

const insertReservation = `-- name: InsertReservation :exec
INSERT INTO stock_reservations (id) VALUES ($1)
`

// The idempotency gate: the PK on id rejects a duplicate reservation_id.
func (q *Queries) InsertReservation(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, insertReservation, id)
	return err
}

const insertReservationItem = `-- name: InsertReservationItem :exec
INSERT INTO reservation_items (reservation_id, product_id, quantity)
VALUES ($1, $2, $3)
`

type InsertReservationItemParams struct {
	ReservationID pgtype.UUID
	ProductID     pgtype.UUID
	Quantity      int32
}

func (q *Queries) InsertReservationItem(ctx context.Context, arg InsertReservationItemParams) error {
	_, err := q.db.Exec(ctx, insertReservationItem, arg.ReservationID, arg.ProductID, arg.Quantity)
	return err
}

const listProducts = `-- name: ListProducts :many
SELECT id, sku, name, description, price_cents, currency, category_id, created_at FROM products
WHERE $3::uuid IS NULL
   OR category_id = $3
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListProductsParams struct {
	Limit      int32
	Offset     int32
	CategoryID pgtype.UUID
}

// Optional category filter via a nullable named arg: when category_id is NULL the
// first branch short-circuits and every row matches.
func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts, arg.Limit, arg.Offset, arg.CategoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Sku,
			&i.Name,
			&i.Description,
			&i.PriceCents,
			&i.Currency,
			&i.CategoryID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsWithInventory = `-- name: ListProductsWithInventory :many
SELECT p.id, p.sku, p.name, p.description, p.price_cents, p.currency, p.category_id, p.created_at, i.quantity, i.reserved, (i.quantity - i.reserved)::int AS available
FROM products p
JOIN inventory i ON i.product_id = p.id
WHERE $3::uuid IS NULL
   OR p.category_id = $3
ORDER BY p.created_at DESC
LIMIT $1 OFFSET $2
`

type ListProductsWithInventoryParams struct {
	Limit      int32
	Offset     int32
	CategoryID pgtype.UUID
}

type ListProductsWithInventoryRow struct {
	ID          pgtype.UUID
	Sku         string
	Name        string
	Description string
	PriceCents  int64
	Currency    string
	CategoryID  pgtype.UUID
	CreatedAt   pgtype.Timestamptz
	Quantity    int32
	Reserved    int32
	Available   int32
}

func (q *Queries) ListProductsWithInventory(ctx context.Context, arg ListProductsWithInventoryParams) ([]ListProductsWithInventoryRow, error) {
	rows, err := q.db.Query(ctx, listProductsWithInventory, arg.Limit, arg.Offset, arg.CategoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsWithInventoryRow
	for rows.Next() {
		var i ListProductsWithInventoryRow
		if err := rows.Scan(
			&i.ID,
			&i.Sku,
			&i.Name,
			&i.Description,
			&i.PriceCents,
			&i.Currency,
			&i.CategoryID,
			&i.CreatedAt,
			&i.Quantity,
			&i.Reserved,
			&i.Available,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReservationItems = `-- name: ListReservationItems :many
SELECT product_id, quantity FROM reservation_items WHERE reservation_id = $1
`

type ListReservationItemsRow struct {
	ProductID pgtype.UUID
	Quantity  int32
}

func (q *Queries) ListReservationItems(ctx context.Context, reservationID pgtype.UUID) ([]ListReservationItemsRow, error) {
	rows, err := q.db.Query(ctx, listReservationItems, reservationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReservationItemsRow
	for rows.Next() {
		var i ListReservationItemsRow
		if err := rows.Scan(&i.ProductID, &i.Quantity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseInventory = `-- name: ReleaseInventory :exec
UPDATE inventory
SET reserved = reserved - $1,
    version  = version + 1
WHERE product_id = $2
`

type ReleaseInventoryParams struct {
	Quantity  int32
	ProductID pgtype.UUID
}

// Compensation: give the held units back to "available" (drop reserved).
func (q *Queries) ReleaseInventory(ctx context.Context, arg ReleaseInventoryParams) error {
	_, err := q.db.Exec(ctx, releaseInventory, arg.Quantity, arg.ProductID)
	return err
}

const reserveInventory = `-- name: ReserveInventory :execrows
UPDATE inventory
SET reserved = reserved + $1,
    version  = version + 1
WHERE product_id = $2
  AND quantity - reserved >= $1
`

type ReserveInventoryParams struct {
	Quantity  int32
	ProductID pgtype.UUID
}

// The oversell guard, as ONE atomic statement. Returns rows-affected: 1 if the
// row had enough available stock (quantity - reserved >= qty), 0 otherwise. The
// row is locked for the duration, so concurrent reservers serialize and can never
// both pass the check on the same stock. version is bumped as a change marker.
func (q *Queries) ReserveInventory(ctx context.Context, arg ReserveInventoryParams) (int64, error) {
	result, err := q.db.Exec(ctx, reserveInventory, arg.Quantity, arg.ProductID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setReservationStatus = `-- name: SetReservationStatus :exec
UPDATE stock_reservations SET status = $2 WHERE id = $1
`

type SetReservationStatusParams struct {
	ID     pgtype.UUID
	Status string
}

func (q *Queries) SetReservationStatus(ctx context.Context, arg SetReservationStatusParams) error {
	_, err := q.db.Exec(ctx, setReservationStatus, arg.ID, arg.Status)
	return err
}
