// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Outbox struct {
	ID          pgtype.UUID
	Topic       string
	Payload     []byte
	CreatedAt   pgtype.Timestamptz
	PublishedAt pgtype.Timestamptz
}

type Payment struct {
	ID             pgtype.UUID
	OrderID        pgtype.UUID
	AmountCents    int64
	Currency       string
	Status         string
	Provider       string
	ProviderRef    *string
	IdempotencyKey string
	CreatedAt      pgtype.Timestamptz
}
