// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (order_id, amount_cents, currency, status, provider, idempotency_key)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, order_id, amount_cents, currency, status, provider, provider_ref, idempotency_key, created_at
`

type CreatePaymentParams struct {
	OrderID        pgtype.UUID
	AmountCents    int64
	Currency       string
	Status         string
	Provider       string
	IdempotencyKey string
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.OrderID,
		arg.AmountCents,
		arg.Currency,
		arg.Status,
		arg.Provider,
		arg.IdempotencyKey,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.AmountCents,
		&i.Currency,
		&i.Status,
		&i.Provider,
		&i.ProviderRef,
		&i.IdempotencyKey,
		&i.CreatedAt,
	)
	return i, err
}

const getPaymentByID = `-- name: GetPaymentByID :one
SELECT id, order_id, amount_cents, currency, status, provider, provider_ref, idempotency_key, created_at FROM payments WHERE id = $1
`

func (q *Queries) GetPaymentByID(ctx context.Context, id pgtype.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByID, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.AmountCents,
		&i.Currency,
		&i.Status,
		&i.Provider,
		&i.ProviderRef,
		&i.IdempotencyKey,
		&i.CreatedAt,
	)
	return i, err
}

const getPaymentByIdempotencyKey = `-- name: GetPaymentByIdempotencyKey :one
SELECT id, order_id, amount_cents, currency, status, provider, provider_ref, idempotency_key, created_at FROM payments WHERE idempotency_key = $1
`

func (q *Queries) GetPaymentByIdempotencyKey(ctx context.Context, idempotencyKey string) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByIdempotencyKey, idempotencyKey)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.AmountCents,
		&i.Currency,
		&i.Status,
		&i.Provider,
		&i.ProviderRef,
		&i.IdempotencyKey,
		&i.CreatedAt,
	)
	return i, err
}

const updatePaymentResult = `-- name: UpdatePaymentResult :one
UPDATE payments
SET status = $2, provider_ref = $3
WHERE id = $1
RETURNING id, order_id, amount_cents, currency, status, provider, provider_ref, idempotency_key, created_at
`

type UpdatePaymentResultParams struct {
	ID          pgtype.UUID
	Status      string
	ProviderRef *string
}

func (q *Queries) UpdatePaymentResult(ctx context.Context, arg UpdatePaymentResultParams) (Payment, error) {
	row := q.db.QueryRow(ctx, updatePaymentResult, arg.ID, arg.Status, arg.ProviderRef)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.AmountCents,
		&i.Currency,
		&i.Status,
		&i.Provider,
		&i.ProviderRef,
		&i.IdempotencyKey,
		&i.CreatedAt,
	)
	return i, err
}
